#' kfit
#'
#' kfit creates a kernel estimate using the Nadaraya-Watson kernel estimator. Other estimators can be used upon specification.
#'
#' @param df A dataframe that will be processed.
#' @param x Numeric vector that is the same length as y (default is Index column generated by qclean function).
#' @param y Numeric vector that is the same length as x.
#' @param b The bandwidth of the kernel (set to 0.1 by default).
#' @param w Weight vector for kernel estimation.
#' @param k Character string to indicate kernel function (default is "Nm" for normal kernel)
#' "Ep" for Epanechnikov or "Bw" for Biweight are alternative options
#' @return Returns a dataframe that contains a column with kernel estimates.
#' @export
#' @import stats
#' @import dplyr
#' @import ggplot2
#' @import npmlda

kfit <- function(df, x = Index, y, b = 0.1, w = 1, k = "Nm"){ # b is the bandwidth and w is the weight of observations

  x <- as.character(substitute(x)) # Convert variable names to strings

  y <- as.character(substitute(y))

  df$kernel <- kernel.fit(seq(1, nrow(df), 1), df[[x]], df[[y]], bw = b, Kernel = k, Wt = w) # Create kernel estimates using Index by default and normal kernel function (Nadaraya-Watson kernel estimator) and add as a new column

  return(df)
}
